include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-raw-types: true
    strict-inference: true
    strict-casts: true
  errors:
    missing_required_param: error
    missing_return: error
    todo: ignore
  exclude:

# https://dart-lang.github.io/linter/lints/
linter:
  rules:
    - prefer_final_locals