name: flutter_cube
description: A Flutter 3D widget that renders Wavefront's object files.
version: 0.1.0
homepage: https://github.com/zesage/flutter_cube

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  vector_math: any

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter

flutter: