name: flutter_cube
description: A Flutter 3D widget that renders Wavefront's object files.
version: 0.1.0
homepage: https://github.com/zesage/flutter_cube

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  vector_math: any
  path: ^1.8.3

dev_dependencies:
  flutter_lints: ^2.0.3
  flutter_test:
    sdk: flutter

flutter: